####################################
#config.yml
####################################
#Allows for non-technically oriented people to edit controlled burn factors and region variables
#without getting deep into our codebase
####################################

#Scoring variables
temp_max: 40
temp_min: 60
wspeed_max: 3
wspeed_min: 7

#Region variables
#Check Region
check_lat: 42.0987
check_long: -75.9180
#Scan Region
start_lat: 41.0987
end_lat: 42.0987
start_long: -76.9180
end_long: -75.9180

#Data analysis variables
num_ranked_regions: 10
num_goroutines: 8

#Timing synchronization (in ms)
request_delay: 37
scanner_delay: 59


#Output logging and monitoring
log_file: log.txt
output_file: results.txt
processing_interval: 100

####################################
#Other factors we may consider in the future
#days_since_rain:
#humidity_min:
#humidity_max:
#foliage_level:
#min_alt:
####################################
